services:
  # backend:
  #   build: ./src
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - .env

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
